import { State } from './types';

export const US_STATES: State[] = [
  { code: 'AL', name: 'Alabama', passingScore: 80 },
  { code: 'AK', name: 'Alaska', passingScore: 80 },
  { code: 'AZ', name: 'Arizona', passingScore: 80 },
  { code: 'AR', name: 'Arkansas', passingScore: 80 },
  { code: 'CA', name: 'California', passingScore: 83 },
  { code: 'CO', name: 'Colorado', passingScore: 80 },
  { code: 'CT', name: 'Connecticut', passingScore: 80 },
  { code: 'DE', name: 'Delaware', passingScore: 80 },
  { code: 'FL', name: 'Florida', passingScore: 80 },
  { code: 'GA', name: 'Georgia', passingScore: 75 },
  { code: 'HI', name: 'Hawaii', passingScore: 80 },
  { code: 'ID', name: 'Idaho', passingScore: 80 },
  { code: 'IL', name: 'Illinois', passingScore: 80 },
  { code: 'IN', name: 'Indiana', passingScore: 80 },
  { code: 'IA', name: 'Iowa', passingScore: 80 },
  { code: 'KS', name: 'Kansas', passingScore: 80 },
  { code: 'KY', name: 'Kentucky', passingScore: 80 },
  { code: 'LA', name: 'Louisiana', passingScore: 80 },
  { code: 'ME', name: 'Maine', passingScore: 80 },
  { code: 'MD', name: 'Maryland', passingScore: 85 },
  { code: 'MA', name: 'Massachusetts', passingScore: 72 },
  { code: 'MI', name: 'Michigan', passingScore: 80 },
  { code: 'MN', name: 'Minnesota', passingScore: 80 },
  { code: 'MS', name: 'Mississippi', passingScore: 80 },
  { code: 'MO', name: 'Missouri', passingScore: 80 },
  { code: 'MT', name: 'Montana', passingScore: 80 },
  { code: 'NE', name: 'Nebraska', passingScore: 80 },
  { code: 'NV', name: 'Nevada', passingScore: 80 },
  { code: 'NH', name: 'New Hampshire', passingScore: 80 },
  { code: 'NJ', name: 'New Jersey', passingScore: 80 },
  { code: 'NM', name: 'New Mexico', passingScore: 80 },
  { code: 'NY', name: 'New York', passingScore: 70 },
  { code: 'NC', name: 'North Carolina', passingScore: 80 },
  { code: 'ND', name: 'North Dakota', passingScore: 80 },
  { code: 'OH', name: 'Ohio', passingScore: 75 },
  { code: 'OK', name: 'Oklahoma', passingScore: 80 },
  { code: 'OR', name: 'Oregon', passingScore: 80 },
  { code: 'PA', name: 'Pennsylvania', passingScore: 83 },
  { code: 'RI', name: 'Rhode Island', passingScore: 80 },
  { code: 'SC', name: 'South Carolina', passingScore: 80 },
  { code: 'SD', name: 'South Dakota', passingScore: 80 },
  { code: 'TN', name: 'Tennessee', passingScore: 80 },
  { code: 'TX', name: 'Texas', passingScore: 70 },
  { code: 'UT', name: 'Utah', passingScore: 80 },
  { code: 'VT', name: 'Vermont', passingScore: 80 },
  { code: 'VA', name: 'Virginia', passingScore: 80 },
  { code: 'WA', name: 'Washington', passingScore: 80 },
  { code: 'WV', name: 'West Virginia', passingScore: 76 },
  { code: 'WI', name: 'Wisconsin', passingScore: 80 },
  { code: 'WY', name: 'Wyoming', passingScore: 80 },
];