"""add_new_field

Revision ID: cf2dcaf796b2
Revises: 20251009_174822
Create Date: 2025-10-09 12:53:16.137979

"""
from alembic import op
import sqlalchemy as sa


revision = 'cf2dcaf796b2'
down_revision = '20251009_174822'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
